grid_map_topic: /grid_map_dso_demo/grid_map
grid_map_visualizations:
  - name: elevation_points
    type: point_cloud
    params:
     layer: maxHeight
  - name: elevation_grid
    type: occupancy_grid
    params:
     layer: maxHeight
     data_min: 0.08
     data_max: -0.16
  - name: occupancy_grid
    type: occupancy_grid
    params:
     layer: OccupancyMap
     data_min: 0
     data_max: 1
  - name: elevation_cells
    type: grid_cells
    params:
     layer: maxHeight
     lower_threshold: -0.08
     upper_threshold: 0.0